// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.saddaadda.domain;

import in.saddaadda.domain.ItemDetailsPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ItemDetailsPK_Roo_Configurable {
    
    declare @type: ItemDetailsPK: @Configurable;
    
}
