// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.saddaadda.domain;

import in.saddaadda.domain.ItemDetailsPK;
import java.io.Serializable;

privileged aspect ItemDetailsPK_Roo_Serializable {
    
    declare parents: ItemDetailsPK implements Serializable;
    
    private static final long ItemDetailsPK.serialVersionUID = 1L;
    
}
