// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.saddaadda.domain;

import in.saddaadda.domain.TransactionSummaryPK;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect TransactionSummaryPK_Roo_Configurable {
    
    declare @type: TransactionSummaryPK: @Configurable;
    
}
