// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package in.saddaadda.domain;

import in.saddaadda.domain.TransactionSummaryPK;
import java.io.Serializable;

privileged aspect TransactionSummaryPK_Roo_Serializable {
    
    declare parents: TransactionSummaryPK implements Serializable;
    
    private static final long TransactionSummaryPK.serialVersionUID = 1L;
    
}
